---
- name: Deploy the zoopla scraper
  hosts: all
  tasks:
    - name: Clone scraper repo
      git:
        repo: https://github.com/MihaiBlebea/jobs_scraper.git
        dest: /home/pi/jobs_scraper
        clone: yes
        update: yes

    - name: Install the software
      shell:
        cmd: ./install.sh
        chdir: /home/pi/jobs_scraper
      register: out

    - debug: var=out.stdout_lines

    - name: Creates a daily cronjob
      cron:
        name: "execute scraper"
        minute: "0"
        hour: "8"
        job: "cd ${HOME}/jobs_scraper && ./execute.sh >> ${HOME}/jobs_scraper.log 2>&1"

    - name: Create the virtual env
      shell:
        cmd: make venv-create
        chdir: /home/pi/jobs_scraper
      register: out

    - debug: var=out.stdout_lines

    - name: Install the dependencies in virtualenv
      shell:
        cmd: ./virtualenv/bin/pip3 install -r requirements.txt
        chdir: /home/pi/jobs_scraper
      register: out

    - debug: var=out.stdout_lines

    - name: Start the API server
      shell:
        cmd: ./virtualenv/bin/python3 ./src/api.py &
        chdir: /home/pi/jobs_scraper